services:
  app:
    container_name: nest-app
    build:
      context: .
      target: ${STAGE:-development}
      dockerfile: dockerfile
    volumes:
      # Only mount source code in development mode
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    restart: always
    ports:
      - ${PORT:-3000}:3000
      # Debug port (only exposed when STAGE=debug)
      - ${DEBUG_PORT:-9229}:9229
    env_file:
      - .env
    environment:
      APP_NAME: ${APP_NAME}
      PORT: ${PORT:-3000}
      APP_URL: ${APP_URL}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_DIALECT: ${DATABASE_DIALECT:-postgres}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_TEST: ${MAIL_TEST}
      DISK_CONFIG: ${DISK_CONFIG}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      JWT_EXPIRATION_TIME_RECOVER_PASSWORD: ${JWT_EXPIRATION_TIME_RECOVER_PASSWORD}

  db:
    container_name: db
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - db-vol:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-vol:
    external: false
